//go:build ignore

// gen-keysyms generates keysym tables from X11 header files.
//
// Usage:
//
//	go run cmd/gen-keysyms/main.go > keysym_generated.go
package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type keysym struct {
	name    string
	value   uint32
	unicode rune // 0 if no unicode mapping
	comment string
	isAlias bool
}

func main() {
	keysyms := make(map[uint32]keysym)
	aliases := make(map[string]uint32) // name -> value

	// Parse keysymdef.h
	parseHeader("/usr/include/X11/keysymdef.h", "XK_", keysyms, aliases)

	// Parse XF86keysym.h
	parseHeader("/usr/include/X11/XF86keysym.h", "XF86XK_", keysyms, aliases)

	// Generate Go code
	generateCode(keysyms, aliases)
}

var (
	// #define XK_BackSpace  0xff08  /* U+0008 BACKSPACE */
	defineRE = regexp.MustCompile(`^#define\s+(\w+)\s+(0x[0-9a-fA-F]+)\s*(?:/\*(.+)\*/)?`)
	// U+XXXX in comment
	unicodeRE = regexp.MustCompile(`U\+([0-9A-Fa-f]{4,6})`)
	// alias for in comment
	aliasRE = regexp.MustCompile(`alias for (\w+)`)
	// deprecated alias
	deprecatedAliasRE = regexp.MustCompile(`deprecated alias`)
)

func parseHeader(path, prefix string, keysyms map[uint32]keysym, aliases map[string]uint32) {
	file, err := os.Open(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: cannot open %s: %v\n", path, err)
		return
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()

		match := defineRE.FindStringSubmatch(line)
		if match == nil {
			continue
		}

		name := match[1]
		if !strings.HasPrefix(name, prefix) {
			continue
		}

		// Remove prefix for the Go name
		goName := strings.TrimPrefix(name, prefix)

		valueStr := match[2]
		value, err := strconv.ParseUint(valueStr, 0, 32)
		if err != nil {
			continue
		}

		comment := ""
		if len(match) > 3 {
			comment = strings.TrimSpace(match[3])
		}

		// Check if this is an alias
		isAlias := aliasRE.MatchString(comment) || deprecatedAliasRE.MatchString(comment)

		// Extract unicode mapping from comment
		var unicode rune
		if unicodeMatch := unicodeRE.FindStringSubmatch(comment); unicodeMatch != nil {
			if u, err := strconv.ParseUint(unicodeMatch[1], 16, 32); err == nil {
				unicode = rune(u)
			}
		}

		ks := keysym{
			name:    goName,
			value:   uint32(value),
			unicode: unicode,
			comment: comment,
			isAlias: isAlias,
		}

		// Only store canonical (non-alias) keysyms in the main map
		if !isAlias {
			if existing, ok := keysyms[uint32(value)]; ok {
				// Keep the first (canonical) name
				_ = existing
			} else {
				keysyms[uint32(value)] = ks
			}
		}

		// Store all names (including aliases) for name->value lookup
		aliases[goName] = uint32(value)
	}
}

func generateCode(keysyms map[uint32]keysym, aliases map[string]uint32) {
	fmt.Println("// Code generated by gen-keysyms. DO NOT EDIT.")
	fmt.Println("//go:generate go run cmd/gen-keysyms/main.go")
	fmt.Println()
	fmt.Println("package xkb")
	fmt.Println()

	// Sort keysyms by value for consistent output
	var values []uint32
	for v := range keysyms {
		values = append(values, v)
	}
	sort.Slice(values, func(i, j int) bool { return values[i] < values[j] })

	// Generate keysymNames map
	fmt.Println("// generatedKeysymNames maps keysym values to canonical names.")
	fmt.Println("var generatedKeysymNames = map[Keysym]string{")
	for _, v := range values {
		ks := keysyms[v]
		// Skip very common ones that are in the manual table
		fmt.Printf("\t0x%08x: %q,\n", v, ks.name)
	}
	fmt.Println("}")
	fmt.Println()

	// Sort aliases by name for consistent output
	var names []string
	for n := range aliases {
		names = append(names, n)
	}
	sort.Strings(names)

	// Generate keysymsByName map
	fmt.Println("// generatedKeysymsByName maps keysym names to values.")
	fmt.Println("var generatedKeysymsByName = map[string]Keysym{")
	for _, n := range names {
		v := aliases[n]
		fmt.Printf("\t%q: 0x%08x,\n", n, v)
	}
	fmt.Println("}")
	fmt.Println()

	// Generate unicode mapping for keysyms that have explicit unicode
	fmt.Println("// generatedKeysymToUnicode maps keysyms to unicode codepoints.")
	fmt.Println("// Only includes keysyms with explicit unicode mappings in the headers.")
	fmt.Println("var generatedKeysymToUnicode = map[Keysym]rune{")
	for _, v := range values {
		ks := keysyms[v]
		if ks.unicode != 0 {
			// Skip Latin-1 range (they map directly)
			if v >= 0x20 && v <= 0xff {
				continue
			}
			// Skip Unicode keysyms (0x01000000+)
			if v >= 0x01000000 {
				continue
			}
			// Skip control characters (U+0000-U+001F and U+007F-U+009F)
			// These are action keys like Return, Tab, Backspace that don't produce text
			if ks.unicode <= 0x001f || (ks.unicode >= 0x007f && ks.unicode <= 0x009f) {
				continue
			}
			fmt.Printf("\t0x%08x: 0x%04x, // %s\n", v, ks.unicode, ks.name)
		}
	}
	fmt.Println("}")
}
